insert into catalog(product_id, product_name, stock, unit_price)
    values ('CATALOG-001','ice-cream',100, 1500)
insert into catalog(product_id, product_name, stock, unit_price)
values ('CATALOG-002','snack',110, 2000)
insert into catalog(product_id, product_name, stock, unit_price)
values ('CATALOG-003','hard',120, 3000)